### ISSUE TITLE
Adjust views of index page according to user login [ranklist]

### ISSUE THREAD

**Issue by peanut11** [kfwong/cs3226-lab#46] opened 2017-03-03 04:39 UTC
- not login: show only top 7 students 
- login with student [rank i ]: show top 7 + student + another student [rank i - 1]
- login with admin: entire ranklist + CRUD privilege

**Comment by kfwong** [comment] 2017-03-05 23:59
duplicate of #48 

#52 fixed.

**Closed as completed by kfwong** 2017-03-05 23:59 UTC
Labels: Requirement
